spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live_score_db
    username: root
    password:
    hikari:
      maximum-pool-size: 100
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

scheduler:
  interval:
    fetch_live_score: 300000 # 5 min

url:
  live_score: http://static.cricinfo.com/rss/livescores.xml

server:
  port: 8080